### ISSUE TITLE
Approvazione project plan v1.0

### ISSUE THREAD

**Issue by Annalisa2** [yousef-shoeib/MAY#1]
Abbiamo caricato la versione 1.0 del project plan da approvare.

**Comment by garganti** [comment]
ok, va bene. Va bene anche usare LWJGL o JOGL, però tenete presente che ci sono librerie java 3d più avanzate (guardate qui https://stackoverflow.com/questions/1197791/best-3d-java-engine) in modo da giustificare le vostre scelte. Buon lavoro
